sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: S9KOnvGirZiGILGLirOUFiV2zBRZ5sEThE9R5/tjS0S8pw+W0fBSMSdA0LLegFCJV0HGGX+7Pkaw8X1iieGJgVm+rHL61c6t6ZMu9q6/b/4+k9Oa8NYEwyUXg7mwSBmckb0hwEaK8GWCv+zYuRzO/Eo5hAo9+bECGTnTeBB9jf+UmnlPEZ7R42uIImNfz+C7q6WAf8oKZCSbuK1dYLD5ivlybkH1mKqX22BXdBq+3QQ1EPXwhJfOhNP3tj/NXPNcOF15eU3OQltXTLJRbJthAJfTlwztQB5xeilDYpBRdyxNIwkOyy+wr056i8m/lw+UBAfgpho7oys5s37tKp54EuP6RBldkEebQKVZGDkYZ+OrtJz1YU2w+xmUWq1bEYCTbEc5MMU4mpNxdLtbPfdK73T+aI4oCx9bTadJsg8QnOx/IgNIl94fFOswZUKLxMf8V9t6PsTJNAr05yYOYgce1BmqlS9C7dNCVqzbGqISrUzIeZpQ6aGPgpB8Eu4TvwppTJdl8wmGQhmOxKLN/NDRSidoi9/3CbRTRRl5uPqIMC1VUV6gHL9GK44YXa24vlHIFHm9HZttECLn6Bj/00zUeiqlvemieJVB+TsU51fx/lXLNKKc8onNROfYPMO7Qm/BeYGQ8w7VVeiTO2iCih+/Bk8q6nWURnvan+WBKcL+5go=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Tales-and-Novels-of-J-de-La-Fontaine-Volume-25_5299
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy